# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SystemNEO430.xdc

# Block Designs: bd/SystemNEO430/SystemNEO430.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystemNEO430 || ORIG_REF_NAME==SystemNEO430} -quiet] -quiet

# IP: bd/SystemNEO430/ip/SystemNEO430_neo430_top_0_0/SystemNEO430_neo430_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SystemNEO430_neo430_top_0_0 || ORIG_REF_NAME==SystemNEO430_neo430_top_0_0} -quiet] -quiet

# XDC: c:/Projects/LabZSC/zsc-lab-1-neo430-display-pdabal/neo430-display.gen/sources_1/bd/SystemNEO430/SystemNEO430_ooc.xdc
